### ISSUE TITLE
Its possible to select the same team on the select screen

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#102] opened 2015-10-21 23:03 UTC
![image](https://cloud.githubusercontent.com/assets/11168751/10652668/72cfc1b2-7826-11e5-986f-72535043c8c0.png)

**Comment by BenGoulet** [comment] 2015-10-22 00:33
Duplicate of https://github.com/symbol24/ProjectJuice/issues/77 ?

**Comment by symbol24** [comment] 2015-10-31 19:56
yes duplicate

**Closed as completed by symbol24** 2015-10-31 19:56 UTC
Labels: duplicate
